INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_therapist_sara', 'د. سارة محمد', 'sara@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'THERAPIST', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `TherapistProfile` (`id`, `userId`, `bio`, `specializations`, `languages`, `pricePerSession`, `yearsExperience`, `rating`, `reviewCount`, `isVerified`, `isAvailable`, `createdAt`, `updatedAt`) VALUES ('profile_cl_therapist_sara', 'cl_therapist_sara', 'أخصائية نفسية سريرية متخصصة في علاج القلق والاكتئاب واضطرابات المزاج. خبرة 8 سنوات في العيادات والاستشارات أونلاين.', '["القلق والتوتر","الاكتئاب","نوبات الهلع"]', 'العربية', 400, 8, 4.9, 127, true, true, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;

INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_therapist_ahmed', 'د. أحمد حسن', 'ahmed@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'THERAPIST', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `TherapistProfile` (`id`, `userId`, `bio`, `specializations`, `languages`, `pricePerSession`, `yearsExperience`, `rating`, `reviewCount`, `isVerified`, `isAvailable`, `createdAt`, `updatedAt`) VALUES ('profile_cl_therapist_ahmed', 'cl_therapist_ahmed', 'معالج نفسي متخصص في العلاقات الزوجية والأسرية. أساعد الأزواج على بناء تواصل صحي وحل النزاعات.', '["العلاقات الزوجية","الإرشاد الأسري","النمو الشخصي"]', 'العربية', 350, 6, 4.8, 89, true, true, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;

INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_therapist_nora', 'د. نورا إبراهيم', 'nora@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'THERAPIST', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `TherapistProfile` (`id`, `userId`, `bio`, `specializations`, `languages`, `pricePerSession`, `yearsExperience`, `rating`, `reviewCount`, `isVerified`, `isAvailable`, `createdAt`, `updatedAt`) VALUES ('profile_cl_therapist_nora', 'cl_therapist_nora', 'أخصائية نفسية للأطفال والمراهقين. خبرة في التعامل مع صعوبات التعلم والتنمر واضطرابات السلوك.', '["مشكلات الأطفال والمراهقين","الصدمات النفسية","الثقة بالنفس"]', 'العربية', 380, 10, 5, 156, true, true, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;

INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_therapist_karim', 'د. كريم عبدالله', 'karim@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'THERAPIST', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `TherapistProfile` (`id`, `userId`, `bio`, `specializations`, `languages`, `pricePerSession`, `yearsExperience`, `rating`, `reviewCount`, `isVerified`, `isAvailable`, `createdAt`, `updatedAt`) VALUES ('profile_cl_therapist_karim', 'cl_therapist_karim', 'استشاري نفسي متخصص في الإدمان والاحتراق الوظيفي وإدارة الضغوط. نهج علاجي معرفي سلوكي.', '["الإدمان","الاحتراق الوظيفي","ضغوط العمل"]', 'العربية', 320, 5, 4.7, 64, true, true, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;

INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_therapist_layla', 'د. ليلى فاروق', 'layla@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'THERAPIST', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `TherapistProfile` (`id`, `userId`, `bio`, `specializations`, `languages`, `pricePerSession`, `yearsExperience`, `rating`, `reviewCount`, `isVerified`, `isAvailable`, `createdAt`, `updatedAt`) VALUES ('profile_cl_therapist_layla', 'cl_therapist_layla', 'معالجة نفسية متخصصة في اضطرابات الأكل والصورة الذاتية والوسواس القهري.', '["الوسواس القهري","النمو الشخصي","الاكتئاب"]', 'العربية', 360, 7, 4.9, 98, true, true, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;

INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `phone`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_patient_1', 'محمد علي', 'patient@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'PATIENT', '01012345678', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `User` (`id`, `name`, `email`, `password`, `role`, `isSuspended`, `createdAt`, `updatedAt`) VALUES ('cl_admin_1', 'مدير النظام', 'admin@nafsi.com', '$2b$12$SZWBePR5NVh6uh710bkMTetTj.2R7mXTHWtD6QJNsL3KGtRd98UXy', 'ADMIN', false, NOW(), NOW()) ON DUPLICATE KEY UPDATE `id`=`id`;
